### ISSUE TITLE
有部分url和id使用json参数不能正常返回

### ISSUE THREAD

**Issue by sooooooooooooooooootheby** [Suxiaoqinx/Netease_url#9]
红框的参数会返回500 绿框的参数可以正常解析

如果更改type为down或者text就可以返回参数

![image](https://github.com/user-attachments/assets/a33f4445-e9c1-407e-b6ee-854065f5d7b7)

![image](https://github.com/user-attachments/assets/c3ff7f8a-ee92-4b1c-9069-2ac3a164d4a8)

这是控制台输出的报错

``` bash
[2024-12-10 14:12:46,900] ERROR in app: Exception on /Song_V1 [GET]
Traceback (most recent call last):
  File "C:\Users\AliceClodia\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\AliceClodia\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\AliceClodia\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\AliceClodia\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\AliceClodia\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\AliceClodia\Desktop\Netease_url\main.py", line 198, in Song_v1
    "tlyric": lyricv1['tlyric']['lyric']
              ~~~~~~~^^^^^^^^^^
KeyError: 'tlyric'
127.0.0.1 - - [10/Dec/2024 14:12:46] "GET /Song_V1?level=standard&type=json&url=https://music.163.com/song?id=2074454693%26userid=480428722 HTTP/1.1" 500 -
```

**Comment by Suxiaoqinx** [comment]
因为2074454693歌曲没有翻译歌词 所以才会返回这个报错
后面会逐一修复
